/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IngredientsIndexRouteImport } from './routes/ingredients/index'
import { Route as IngredientsIngredientNameIndexRouteImport } from './routes/ingredients/$ingredientName/index'
import { Route as IngredientsIngredientNameMealsMealIdRouteImport } from './routes/ingredients/$ingredientName/meals/$mealId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsIndexRoute = IngredientsIndexRouteImport.update({
  id: '/ingredients/',
  path: '/ingredients/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsIngredientNameIndexRoute =
  IngredientsIngredientNameIndexRouteImport.update({
    id: '/ingredients/$ingredientName/',
    path: '/ingredients/$ingredientName/',
    getParentRoute: () => rootRouteImport,
  } as any)
const IngredientsIngredientNameMealsMealIdRoute =
  IngredientsIngredientNameMealsMealIdRouteImport.update({
    id: '/ingredients/$ingredientName/meals/$mealId',
    path: '/ingredients/$ingredientName/meals/$mealId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ingredients/': typeof IngredientsIndexRoute
  '/ingredients/$ingredientName/': typeof IngredientsIngredientNameIndexRoute
  '/ingredients/$ingredientName/meals/$mealId': typeof IngredientsIngredientNameMealsMealIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ingredients': typeof IngredientsIndexRoute
  '/ingredients/$ingredientName': typeof IngredientsIngredientNameIndexRoute
  '/ingredients/$ingredientName/meals/$mealId': typeof IngredientsIngredientNameMealsMealIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ingredients/': typeof IngredientsIndexRoute
  '/ingredients/$ingredientName/': typeof IngredientsIngredientNameIndexRoute
  '/ingredients/$ingredientName/meals/$mealId': typeof IngredientsIngredientNameMealsMealIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ingredients/'
    | '/ingredients/$ingredientName/'
    | '/ingredients/$ingredientName/meals/$mealId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ingredients'
    | '/ingredients/$ingredientName'
    | '/ingredients/$ingredientName/meals/$mealId'
  id:
    | '__root__'
    | '/'
    | '/ingredients/'
    | '/ingredients/$ingredientName/'
    | '/ingredients/$ingredientName/meals/$mealId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IngredientsIndexRoute: typeof IngredientsIndexRoute
  IngredientsIngredientNameIndexRoute: typeof IngredientsIngredientNameIndexRoute
  IngredientsIngredientNameMealsMealIdRoute: typeof IngredientsIngredientNameMealsMealIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/': {
      id: '/ingredients/'
      path: '/ingredients'
      fullPath: '/ingredients/'
      preLoaderRoute: typeof IngredientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/$ingredientName/': {
      id: '/ingredients/$ingredientName/'
      path: '/ingredients/$ingredientName'
      fullPath: '/ingredients/$ingredientName/'
      preLoaderRoute: typeof IngredientsIngredientNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/$ingredientName/meals/$mealId': {
      id: '/ingredients/$ingredientName/meals/$mealId'
      path: '/ingredients/$ingredientName/meals/$mealId'
      fullPath: '/ingredients/$ingredientName/meals/$mealId'
      preLoaderRoute: typeof IngredientsIngredientNameMealsMealIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IngredientsIndexRoute: IngredientsIndexRoute,
  IngredientsIngredientNameIndexRoute: IngredientsIngredientNameIndexRoute,
  IngredientsIngredientNameMealsMealIdRoute:
    IngredientsIngredientNameMealsMealIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
